name: Labeler
on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
  complete:
    runs-on: self-hosted

    steps:
      - run: build.sh
        working-directory: ./scripts
      - run: test.sh.sh
        working-directory: ./scripts
      - run: publish.sh
        working-directory: ./scripts